export const EVENT_VOCABULARY_VERSION = 'v2';

export type RuntimeEventSeverity = 'info' | 'warn' | 'error';

export const CANONICAL_EVENT = {
  workflow: {
    reloadSucceeded: 'workflow.reload.succeeded',
    reloadFailed: 'workflow.reload.failed',
    pathSwitched: 'workflow.path.switched',
    reloadForced: 'workflow.reload.forced'
  },
  codex: {
    sessionStarted: 'codex.session.started',
    promptSent: 'codex.prompt.sent',
    turnStarted: 'codex.turn.started',
    phasePlanning: 'codex.phase.planning',
    phaseImplementation: 'codex.phase.implementation',
    phaseValidation: 'codex.phase.validation',
    turnCompleted: 'codex.turn.completed',
    turnFailed: 'codex.turn.failed',
    turnCancelled: 'codex.turn.cancelled',
    turnTimedOut: 'codex.turn.timed_out',
    turnInputRequired: 'codex.turn.input_required',
    startupFailed: 'codex.startup.failed',
    approvalAutoApproved: 'codex.approval.auto_approved',
    toolInputAutoAnswered: 'codex.tool_input.auto_answered',
    toolCallStarted: 'codex.tool.started',
    toolCallCompleted: 'codex.tool.completed',
    toolCallFailed: 'codex.tool.failed',
    dynamicToolCapabilityMismatch: 'codex.tool.dynamic_capability_mismatch',
    unsupportedToolCall: 'codex.tool.unsupported',
    unsupportedServerRequest: 'codex.protocol.unsupported_request',
    protocolMalformedLine: 'codex.protocol.malformed_line',
    protocolWarning: 'codex.protocol.warning',
    rateLimitsUpdated: 'codex.rate_limits.updated',
    modelRerouted: 'codex.model.rerouted',
    threadActivityUpdated: 'codex.thread.activity_updated',
    transcriptLookup: 'codex.transcript.lookup',
    sideOutput: 'codex.side_output',
    turnWaiting: 'codex.turn.waiting',
    commandLegacyPathUsed: 'codex.command.legacy_path_used',
    commandMixedTypedOverridesApplied: 'codex.command.mixed_typed_overrides_applied',
    tokenTelemetryMissingThresholdExceeded: 'token_telemetry_missing_threshold_exceeded'
  },
  budget: {
    warningThresholdCrossed: 'budget.warning_threshold_crossed',
    hardLimitExceeded: 'budget.hard_limit_exceeded',
    telemetryUnavailable: 'budget.telemetry_unavailable'
  },
  orchestration: {
    dispatchValidationFailed: 'orchestration.dispatch.validation.failed',
    dispatchValidationRecovered: 'orchestration.dispatch.validation.recovered',
    dispatchBackpressureActive: 'orchestration.dispatch.backpressure.active',
    dispatchAttemptStarted: 'orchestration.dispatch.attempt.started',
    dispatchDuplicateSkipped: 'orchestration.dispatch.duplicate.skipped',
    dispatchSpawnSucceeded: 'orchestration.dispatch.spawn.succeeded',
    dispatchSpawnFailed: 'orchestration.dispatch.spawn.failed',
    retryScheduled: 'orchestration.retry.scheduled',
    retryTimerCallbackFailed: 'orchestration.retry_timer.callback_failed',
    workerExitHandled: 'orchestration.worker.exit.handled',
    workerTerminated: 'orchestration.worker.terminated',
    workerEvent: 'orchestration.worker.event',
    staleWorkerEventIgnored: 'orchestration.worker_event.stale_ignored',
    staleWorkerExitIgnored: 'orchestration.worker_exit.stale_ignored',
    ownershipConflictDetected: 'orchestration.ownership.conflict_detected',
    workerStalled: 'orchestration.worker.stalled',
    workerHostSlotsExhausted: 'orchestration.worker.host_slots_exhausted',
    blockedInputScheduled: 'orchestration.blocked_input.scheduled',
    blockedInputSubmitRequested: 'orchestration.blocked_input.submit.requested',
    blockedInputSubmitRejected: 'orchestration.blocked_input.submit.rejected',
    blockedInputSubmitNativeApplied: 'orchestration.blocked_input.submit.native_applied',
    blockedInputSubmitNativeFailed: 'orchestration.blocked_input.submit.native_failed',
    blockedInputSubmitFallbackUsed: 'orchestration.blocked_input.submit.fallback_used',
    blockedInputResumed: 'orchestration.blocked_input.resumed',
    blockedInputCleared: 'orchestration.blocked_input.cleared',
    blockedWorkerEventQuarantined: 'orchestration.blocked_worker_event.quarantined',
    missingToolOutputRecoveryStarted: 'orchestration.missing_tool_output_recovery.started',
    missingToolOutputRecoveryInterruptCompleted: 'orchestration.missing_tool_output_recovery.interrupt_completed',
    missingToolOutputRecoveryStartFailed: 'orchestration.missing_tool_output_recovery.start_failed',
    missingToolOutputRecoveryBlocked: 'orchestration.missing_tool_output_recovery.blocked',
    agentReviewHandoffProgressObserved: 'orchestration.agent_review_handoff_progress_observed',
    noProgressBlockSuppressed: 'orchestration.no_progress_block_suppressed',
    staleBlockedInputCleared: 'orchestration.stale_blocked_input_cleared',
    freshDispatchAfterReviewHandoff: 'orchestration.fresh_dispatch_after_review_handoff',
    redispatchCircuitBreakerOpened: 'orchestrator.redispatch.circuit_breaker_opened',
    redispatchCompletionGateBlocked: 'orchestrator.redispatch.completion_gate_blocked',
    cancelToBacklogExecuted: 'orchestrator.cancel_to_backlog.executed',
    stateAwaitingHumanReviewScopeIncomplete: 'orchestrator.state.awaiting_human_review_scope_incomplete',
    phaseMarkerEmitted: 'orchestration.phase_marker.emitted',
    phaseMarkerIgnored: 'orchestration.phase_marker.ignored',
    runningWaitStallThresholdExceeded: 'running_wait_stall_threshold_exceeded'
  },
  progress: {
    heartbeatOnlyDetected: 'runtime.progress.heartbeat_only_detected',
    activeButOpaqueDetected: 'runtime.progress.active_but_opaque_detected',
    stalledWaitingDetected: 'runtime.progress.stalled_waiting_detected'
  },
  agentRunner: {
    attemptStarted: 'agent_runner.attempt.started',
    attemptCompleted: 'agent_runner.attempt.completed',
    attemptFailed: 'agent_runner.attempt.failed'
  },
  workspace: {
    provisionStart: 'workspace.provision.start',
    provisionSuccess: 'workspace.provision.success',
    provisionFailed: 'workspace.provision.failed',
    provisionReused: 'workspace.provision.reused',
    provisionFailureCleanupSucceeded: 'workspace.provision.failure_cleanup.succeeded',
    provisionFailureCleanupFailed: 'workspace.provision.failure_cleanup.failed',
    copyIgnoredStart: 'workspace.copy_ignored.start',
    copyIgnoredSuccess: 'workspace.copy_ignored.success',
    copyIgnoredFailed: 'workspace.copy_ignored.failed',
    finalizationFallback: 'workspace.finalization.fallback',
    teardownStart: 'workspace.teardown.start',
    teardownSuccess: 'workspace.teardown.success',
    teardownFailed: 'workspace.teardown.failed',
    integrityCheckStart: 'workspace.integrity.check.start',
    integrityCheckSuccess: 'workspace.integrity.check.success',
    integrityCheckFailed: 'workspace.integrity.check.failed',
    integrityReconcileStart: 'workspace.integrity.reconcile.start',
    integrityReconcileSuccess: 'workspace.integrity.reconcile.success',
    integrityReconcileFailed: 'workspace.integrity.reconcile.failed',
    staleMetadataPrunedWarning: 'workspace.integrity.stale_metadata_pruned.warning'
    ,
    preflightCleanupApplied: 'workspace.preflight.cleanup.applied',
    preflightConflictDetected: 'workspace.preflight.conflict.detected'
  },
  tracker: {
    candidateFetchFailed: 'tracker.candidates.fetch_failed',
    retryFetchFailed: 'tracker.retry.fetch_failed',
    retryCleared: 'tracker.retry.cleared',
    stateRefreshFailed: 'tracker.state.refresh.failed',
    githubIssueLinkMissing: 'tracker.github_issue_link.missing'
  },
  runtime: {
    argsResolved: 'runtime.args.resolved',
    loggingConfigured: 'runtime.logging.configured',
    securityProfileActive: 'runtime.security.profile.active',
    startupValidationBypassed: 'runtime.startup.validation.bypassed',
    startupStateInitialized: 'runtime.startup.state.initialized',
    startupCleanupCompleted: 'runtime.startup.cleanup.completed',
    startupCleanupFailed: 'runtime.startup.cleanup.failed',
    httpEnabled: 'runtime.http.enabled',
    httpDisabled: 'runtime.http.disabled',
    started: 'runtime.started',
    stopped: 'runtime.stopped',
    guardrailAckRequired: 'runtime.guardrail.ack.required'
  },
  api: {
    serverListening: 'api.server.listening',
    stateRequested: 'api.state.requested',
    stateSnapshotUnavailable: 'api.state.snapshot.unavailable',
    stateSnapshotDegraded: 'api.state.snapshot.degraded',
    refreshRequested: 'api.refresh.requested',
    issueRequested: 'api.issue.requested',
    routeNotFound: 'api.route.not_found',
    methodNotAllowed: 'api.method.not_allowed',
    localError: 'api.error.local',
    internalError: 'api.error.internal',
    degradedRouteNotFound: 'api_degraded_route_not_found',
    degradedSchemaMismatch: 'api_degraded_schema_mismatch'
  },
  persistence: {
    pruned: 'persistence.pruned',
    pruneFailed: 'persistence.prune.failed',
    recordSessionFailed: 'persistence.session.record_failed',
    recordEventFailed: 'persistence.event.record_failed',
    startRunFailed: 'persistence.run.start_failed',
    completeRunFailed: 'persistence.run.complete_failed'
  }
} as const;
