import fs from 'node:fs';
import path from 'node:path';

import { WorkflowLoader } from './loader';
import type { ProfilePack, ProfileResolution } from './profile-registry';
import { ConfigResolver } from './resolver';
import type { ValidationResult } from './types';
import { ConfigValidator } from './validator';

export interface DetectedProjectFacts {
  root: string;
  packageManager?: string | null;
  existingWorkflowPath?: string | null;
}

export interface InitUserChoices {
  dryRun: boolean;
  selections: readonly string[];
}

export type FilePlanAction = 'create' | 'overwrite' | 'skip';
export type FilePlanOverwriteStatus = 'absent' | 'exists' | 'not_checked';

export interface WorkflowFilePlanEntry {
  path: string;
  action: FilePlanAction;
  overwriteStatus: FilePlanOverwriteStatus;
  wouldWrite: boolean;
  content?: string;
  contentPreview: string;
  validationNotes: string[];
  requiresOverwriteApproval: boolean;
}

export interface WorkflowMaterializationPlan {
  dryRun: boolean;
  selections: readonly string[];
  selectedPacks: string[];
  bundleProvenance: Array<{ bundle: string; packs: string[] }>;
  detectedProjectFacts: DetectedProjectFacts;
  files: WorkflowFilePlanEntry[];
  validation: ValidationResult;
}

export interface WorkflowMaterializerOptions {
  resolution: ProfileResolution;
  projectFacts: DetectedProjectFacts;
  choices: InitUserChoices;
  clock?: () => Date;
}

const WORKFLOW_STATE_GITIGNORE = ['*', '!.gitignore', ''].join('\n');

export function materializeWorkflowPlan(options: WorkflowMaterializerOptions): WorkflowMaterializationPlan {
  if (options.resolution.errors.length > 0) {
    throw new Error(options.resolution.errors.join('\n'));
  }
  if (options.resolution.protectedBindings.length > 0) {
    throw new Error('Protected workflow bindings cannot be generated by init. Choose workflow:solo-local or workflow:team-review.');
  }

  const workflowContent = renderGeneratedWorkflow(options);
  const workflowPath = path.join(options.projectFacts.root, 'WORKFLOW.md');
  const workflowValidation = validateWorkflowContent(workflowContent, workflowPath);
  const files: WorkflowFilePlanEntry[] = [
    buildFilePlanEntry({
      root: options.projectFacts.root,
      relativePath: 'WORKFLOW.md',
      content: workflowContent,
      notes: workflowValidation.ok
        ? ['generated workflow parsed and validated successfully']
        : [`generated workflow validation failed: ${workflowValidation.message}`]
    }),
    buildFilePlanEntry({
      root: options.projectFacts.root,
      relativePath: path.join('.symphony', 'system', '.gitignore'),
      content: WORKFLOW_STATE_GITIGNORE,
      notes: ['keeps generated local runtime state out of version control']
    }),
    buildGitignorePlanEntry({
      root: options.projectFacts.root,
      ignorePath: '.gitignore',
      entry: '.symphony/system/'
    })
  ];

  return {
    dryRun: options.choices.dryRun,
    selections: options.choices.selections,
    selectedPacks: options.resolution.packs.map((pack) => pack.id),
    bundleProvenance: options.resolution.expandedBundles.map((expansion) => ({
      bundle: expansion.bundle.id,
      packs: [...expansion.packs]
    })),
    detectedProjectFacts: options.projectFacts,
    files,
    validation: workflowValidation
  };
}

export function materializeWorkflowDryRun(options: WorkflowMaterializerOptions): WorkflowMaterializationPlan {
  return materializeWorkflowPlan({
    ...options,
    choices: { ...options.choices, dryRun: true }
  });
}

export function renderWorkflowFilePlan(plan: WorkflowMaterializationPlan): string {
  const lines = [
    `Symphony init ${plan.dryRun ? 'dry-run' : 'write'} file plan`,
    '',
    `Dry run: ${plan.dryRun ? 'yes' : 'no'}`,
    `Selections: ${plan.selections.join(', ') || '(none)'}`,
    `Selected packs: ${plan.selectedPacks.join(', ')}`,
    `Bundle provenance: ${formatBundleProvenance(plan)}`,
    `Project root: ${plan.detectedProjectFacts.root}`,
    `Writes performed: ${plan.dryRun ? 'no' : 'pending'}`,
    `Validation: ${plan.validation.ok ? 'ok' : `failed (${plan.validation.error_code})`}`,
    '',
    'Files:'
  ];

  for (const [index, file] of plan.files.entries()) {
    lines.push(
      `  ${index + 1}. ${file.path}`,
      `     action: ${file.action}`,
      `     overwrite: ${file.overwriteStatus}`,
      `     would_write: ${file.wouldWrite ? 'yes' : 'no'}`,
      `     overwrite_approval_required: ${file.requiresOverwriteApproval ? 'yes' : 'no'}`,
      `     validation_notes: ${file.validationNotes.join('; ') || 'none'}`,
      '     content:',
      indent(file.content ?? file.contentPreview, '       ')
    );
  }

  return `${lines.join('\n')}\n`;
}

function renderGeneratedWorkflow(options: WorkflowMaterializerOptions): string {
  const dimensions = options.resolution.dimensions;
  const tracker = requirePack(dimensions.tracker, 'tracker');
  const workspace = requirePack(dimensions.workspace, 'workspace');
  const toolchain = requirePack(dimensions.toolchain, 'toolchain');
  const workflow = requirePack(dimensions.workflow, 'workflow');
  const trackerKind = tracker.name;
  const workspaceType = workspace.name;
  const profileName = workflow.name;
  const activeStates = getActiveStates(trackerKind, profileName);
  const handoffStates = getHandoffStates(trackerKind, profileName);
  const freshDispatchStates = getFreshDispatchStates(trackerKind, profileName);
  const terminalStates = getTerminalStates(trackerKind, profileName);
  const bundle = options.resolution.expandedBundles.map((expansion) => expansion.bundle.id).join(',');
  const packs = options.resolution.packs.map((pack) => pack.id).join(',');
  const packageManager = options.projectFacts.packageManager ?? 'unknown';

  return [
    '---',
    'symphony:',
    '  generated_profile:',
    `    profile: ${yamlString(profileName)}`,
    `    bundle: ${yamlString(bundle || 'explicit-packs')}`,
    '    packs:',
    ...options.resolution.packs.map((pack) => `      - ${yamlString(pack.id)}`),
    '    generated_by: "symphony init"',
    'tracker:',
    `  kind: ${yamlString(trackerKind)}`,
    ...trackerCredentialLines(trackerKind),
    `  active_states: ${yamlList(activeStates)}`,
    `  terminal_states: ${yamlList(terminalStates)}`,
    ...optionalTrackerStateLines(handoffStates, freshDispatchStates),
    'workspace:',
    '  provisioner:',
    `    type: ${yamlString(workspaceType)}`,
    ...workspaceProvisionerLines(workspaceType),
    'toolchain:',
    `  kind: ${yamlString(toolchain.name)}`,
    'codex:',
    '  command: codex app-server',
    ...codexSandboxLines(workspaceType),
    'persistence:',
    '  enabled: true',
    'validation:',
    '  ui_evidence_profile: baseline',
    '---',
    `<!-- symphony-generated-profile: profile=${profileName}; bundle=${bundle || 'explicit-packs'}; packs=${packs}; bundle_provenance=${formatBundleProvenanceForComment(options.resolution)}; -->`,
    '',
    '# Symphony Workflow',
    '',
    `Generated by \`symphony init\` for the ${profileName} workflow style.`,
    '',
    '## Selected Packs',
    '',
    ...options.resolution.packs.map((pack) => `- ${pack.id}: ${pack.summary}`),
    '',
    '## Detected Project Facts',
    '',
    '- Project root: .',
    `- Package manager: ${packageManager}`,
    '',
    '## Operator Contract',
    '',
    '- Work one issue at a time and keep progress evidence in the tracker.',
    '- Run the validation commands that match the repository before sharing results.',
    '- For dry-run initialization, review this generated file plan before enabling any write path.',
    '- Keep generated runtime state under .symphony/system/ and out of version control.'
  ].join('\n');
}

function workspaceProvisionerLines(workspaceType: string): string[] {
  return workspaceType === 'worktree' ? ['    repo_root: "."'] : [];
}

function codexSandboxLines(workspaceType: string): string[] {
  if (workspaceType !== 'worktree') {
    return [];
  }
  return ['  thread_sandbox: danger-full-access', '  turn_sandbox_policy: danger-full-access'];
}

function optionalTrackerStateLines(
  handoffStates: readonly string[],
  freshDispatchStates: readonly string[]
): string[] {
  if (handoffStates.length === 0 && freshDispatchStates.length === 0) {
    return [];
  }
  return [`  handoff_states: ${yamlList(handoffStates)}`, `  fresh_dispatch_states: ${yamlList(freshDispatchStates)}`];
}

export function validateWorkflowContent(content: string, workflowPath: string): ValidationResult {
  try {
    const workflowDefinition = new WorkflowLoader().parse(content);
    const effectiveConfig = new ConfigResolver({
      env: {
        GITHUB_REPOSITORY_NAME: 'example-repo',
        GITHUB_REPOSITORY_OWNER: 'example-owner',
        GITHUB_TOKEN: 'validation-token',
        LINEAR_API_KEY: 'validation-token',
        LINEAR_PROJECT_SLUG: 'EXAMPLE'
      },
      homedir: () => path.dirname(workflowPath)
    }).resolve(workflowDefinition, { workflowPath });
    return new ConfigValidator({ clock: () => new Date('2026-05-25T00:00:00.000Z') }).validate(effectiveConfig);
  } catch (error) {
    return {
      ok: false,
      error_code: 'workflow_parse_error',
      message: error instanceof Error ? error.message : String(error),
      at: '2026-05-25T00:00:00.000Z'
    };
  }
}

function getActiveStates(trackerKind: string, profileName: string): string[] {
  if (trackerKind === 'github') {
    return ['Open'];
  }
  return profileName === 'team-review' ? ['Todo', 'In Progress', 'Agent Review'] : ['Todo', 'In Progress'];
}

function getHandoffStates(trackerKind: string, profileName: string): string[] {
  return trackerKind !== 'github' && profileName === 'team-review' ? ['Agent Review'] : [];
}

function getFreshDispatchStates(trackerKind: string, profileName: string): string[] {
  return trackerKind !== 'github' && profileName === 'team-review' ? ['Agent Review'] : [];
}

function getTerminalStates(trackerKind: string, profileName: string): string[] {
  if (trackerKind === 'github') {
    return ['Closed'];
  }
  return profileName === 'team-review' ? ['Done', 'Canceled'] : ['Done'];
}

function trackerCredentialLines(trackerKind: string): string[] {
  if (trackerKind === 'linear') {
    return ['  api_key: "$LINEAR_API_KEY"', '  project_slug: "$LINEAR_PROJECT_SLUG"'];
  }
  if (trackerKind === 'github') {
    return [
      '  api_key: "$GITHUB_TOKEN"',
      '  owner: "$GITHUB_REPOSITORY_OWNER"',
      '  repo: "$GITHUB_REPOSITORY_NAME"'
    ];
  }
  return [];
}

function buildFilePlanEntry(params: {
  root: string;
  relativePath: string;
  content: string;
  notes: string[];
}): WorkflowFilePlanEntry {
  const absolutePath = path.join(params.root, params.relativePath);
  const exists = fs.existsSync(absolutePath);
  const existingContent = exists ? fs.readFileSync(absolutePath, 'utf8') : null;
  const action: FilePlanAction = exists ? (existingContent === params.content ? 'skip' : 'overwrite') : 'create';
  return {
    path: params.relativePath,
    action,
    overwriteStatus: exists ? 'exists' : 'absent',
    wouldWrite: action !== 'skip',
    content: params.content,
    contentPreview: preview(params.content),
    validationNotes: action === 'skip' ? [...params.notes, 'existing content already matches generated content'] : params.notes,
    requiresOverwriteApproval: action === 'overwrite'
  };
}

function buildGitignorePlanEntry(params: { root: string; ignorePath: string; entry: string }): WorkflowFilePlanEntry {
  const absolutePath = path.join(params.root, params.ignorePath);
  const exists = fs.existsSync(absolutePath);
  const existingContent = exists ? fs.readFileSync(absolutePath, 'utf8') : '';
  const lines = existingContent.length > 0 ? existingContent.split('\n') : [];
  const hasEntry = lines.some((line) => line.trim() === params.entry);
  const content = hasEntry ? existingContent : appendGitignoreEntry(existingContent, params.entry);
  const action: FilePlanAction = hasEntry ? 'skip' : exists ? 'overwrite' : 'create';

  return {
    path: params.ignorePath,
    action,
    overwriteStatus: exists ? 'exists' : 'absent',
    wouldWrite: action !== 'skip',
    content,
    contentPreview: preview(content),
    validationNotes: hasEntry
      ? ['root .gitignore already contains .symphony/system/']
      : ['adds .symphony/system/ to keep local runtime state out of version control'],
    requiresOverwriteApproval: false
  };
}

function appendGitignoreEntry(content: string, entry: string): string {
  if (content.length === 0) {
    return `${entry}\n`;
  }
  const separator = content.endsWith('\n') ? '' : '\n';
  return `${content}${separator}${entry}\n`;
}

function requirePack(pack: ProfilePack | undefined, dimension: string): ProfilePack {
  if (!pack) {
    throw new Error(`Missing required ${dimension} pack.`);
  }
  return pack;
}

function preview(content: string): string {
  return content.length <= 400 ? content : `${content.slice(0, 397)}...`;
}

function formatBundleProvenance(plan: WorkflowMaterializationPlan): string {
  if (plan.bundleProvenance.length === 0) {
    return 'explicit-packs';
  }
  return plan.bundleProvenance.map((entry) => `${entry.bundle} -> ${entry.packs.join(', ')}`).join('; ');
}

function formatBundleProvenanceForComment(resolution: ProfileResolution): string {
  if (resolution.expandedBundles.length === 0) {
    return 'explicit-packs';
  }
  return resolution.expandedBundles.map((entry) => `${entry.bundle.id}->${entry.packs.join(',')}`).join('|');
}

function yamlList(values: readonly string[]): string {
  return `[${values.map(yamlString).join(', ')}]`;
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}

function indent(text: string, prefix: string): string {
  return text
    .split('\n')
    .map((line) => `${prefix}${line}`)
    .join('\n');
}
