export let elements: any = {};

export function resolveDashboardElements(doc = document) {
  return {
    connectionBadge: doc.getElementById('connection-badge'),
    connectionDetail: doc.getElementById('connection-detail'),
    lastUpdated: doc.getElementById('last-updated'),
    refreshButton: doc.getElementById('refresh-button'),
    refreshStatus: doc.getElementById('refresh-status'),
    healthMessage: doc.getElementById('health-message'),
    lastError: doc.getElementById('last-error'),
    actionRequiredBanner: doc.getElementById('action-required-banner'),
    actionRequiredTitle: doc.getElementById('action-required-title'),
    actionRequiredSummary: doc.getElementById('action-required-summary'),
    actionRequiredGroups: doc.getElementById('action-required-groups'),
    runtimeStaleBanner: doc.getElementById('runtime-stale-banner'),
    runtimeStaleTitle: doc.getElementById('runtime-stale-title'),
    runtimeStaleSummary: doc.getElementById('runtime-stale-summary'),
    apiDegradedBanner: doc.getElementById('api-degraded-banner'),
    apiDegradedSummary: doc.getElementById('api-degraded-summary'),
    snapshotErrorPanel: doc.getElementById('snapshot-error-panel'),
    snapshotErrorMessage: doc.getElementById('snapshot-error-message'),
    kpiGrid: doc.getElementById('kpi-grid'),
    retryStatusSummary: doc.getElementById('retry-status-summary'),
    rateLimits: doc.getElementById('rate-limits'),
    throughputPanel: doc.getElementById('throughput-panel'),
    throughputOutput: doc.getElementById('throughput-output'),
    runtimeResolutionOutput: doc.getElementById('runtime-resolution-output'),
    runningRows: doc.getElementById('running-rows'),
    retryRows: doc.getElementById('retry-rows'),
    blockedRows: doc.getElementById('blocked-rows'),
    stoppedRunRecoveryList: doc.getElementById('stopped-run-recovery-list'),
    stoppedRunRecoveryLoad: doc.getElementById('stopped-run-recovery-load'),
    projectHistoryProjectKey: doc.getElementById('project-history-project-key'),
    projectHistoryLoad: doc.getElementById('project-history-load'),
    projectHistoryStatus: doc.getElementById('project-history-status'),
    projectHistoryFacts: doc.getElementById('project-history-facts'),
    projectHistoryRows: doc.getElementById('project-history-rows'),
    projectHistoryDetail: doc.getElementById('project-history-detail'),
    statusFilter: doc.getElementById('status-filter'),
    runningFilter: doc.getElementById('running-filter'),
    issuePanel: doc.getElementById('issue-panel'),
    issueInput: doc.getElementById('issue-input'),
    issueLoad: doc.getElementById('issue-load'),
    issueOpenJson: doc.getElementById('issue-open-json'),
    issueSummary: doc.getElementById('issue-summary'),
    issueExplainerCard: doc.getElementById('issue-explainer-card'),
    issueExplainerActionability: doc.getElementById('issue-explainer-actionability'),
    issueExplainerHeadline: doc.getElementById('issue-explainer-headline'),
    issueExplainerClassification: doc.getElementById('issue-explainer-classification'),
    issueExplainerReason: doc.getElementById('issue-explainer-reason'),
    issueExplainerAction: doc.getElementById('issue-explainer-action'),
    issueExplainerTransition: doc.getElementById('issue-explainer-transition'),
    issueExplainerVersion: doc.getElementById('issue-explainer-version'),
    issueExplainerDetail: doc.getElementById('issue-explainer-detail'),
    threadDetail: doc.getElementById('thread-detail'),
    threadTimelineLanes: doc.getElementById('thread-timeline-lanes'),
    threadBlockerCard: doc.getElementById('thread-blocker-card'),
    threadCapabilityWarnings: doc.getElementById('thread-capability-warnings'),
    threadRawEvents: doc.getElementById('thread-raw-events'),
    issueOutput: doc.getElementById('issue-output'),
    runtimeEventsPanel: doc.getElementById('runtime-events-panel'),
    eventFeedFilter: doc.getElementById('event-feed-filter'),
    runtimeEventsList: doc.getElementById('runtime-events-list'),
    diagnosticsOutput: doc.getElementById('diagnostics-output'),
    historyList: doc.getElementById('history-list')
  };
}

export function setDashboardElements(nextElements: any) {
  elements = nextElements;
}
